[package]
name = "xdf"
version = "0.1.0"
edition = "2021"
exclude = ["example-files", "!example-files/minimal.xdf", ".*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.0"
byteorder = "1.4.3"
error-chain = "0.12.4"
log = "0.4.20"
thiserror = "1.0.38"
xmltree = "0.10.3"

[dev-dependencies]
assert_fs = "1.0.10"
glassbench = "0.3.5"

[profile.profiler]
inherits = "release"
debug = true
strip = "none"

[[bench]]
name = "parse_files"
harness = false
