[package]
name = "xdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
error-chain = "0.12.4"
thiserror = "1.0.38"
xmltree = "0.10.3"

[dev-dependencies]
assert_fs = "1.0.10"
